apiVersion: apps/v1
kind: Deployment
metadata:
  name: sve-deployment
  labels:
    app: apolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apolo
  template:
    metadata:
      labels:
        app: apolo
    spec:
      containers:
        - name: sve-container
          image: daagiral/daagiral:latest
          envFrom:
            - configMapRef:
                name: sve-configmap
          ports:
            - containerPort: 8080
