apiVersion: apps/v1
kind: Deployment
metadata:
  name: sve-deployment
  labels:
    app: apolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apolo
  template:
    metadata:
      labels:
        app: apolo
    spec:
      containers:
        - name: sve-container
          image: daagiral/daagiral:latest
          volumeMounts:
            - name: config
              mountPath: /deployments/config
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: sve-configmap
            items:
              - key: application.properties
                path: application.properties