apiVersion: v1
kind: Deployment
metadata:
  name: sve-deployment
  namespace: default
  labels:
    app: apolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apolo
  template:
    metadata:
      labels:
        app: apolo
    spec:
      containers:
        - name: sve-container
          image: daagiral/daagiral:latest
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
          ports:
            - containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: sve-configmap